name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        go: [ '1.17', '1.16', '1.15', '1.14' ]
    name: Go ${{ matrix.go }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      -
        name: Tests
        run: make test

  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      -
        name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      -
        name: E2E tests
        run: make e2e

      -
        name: Build
        uses: goreleaser/goreleaser-action@c127c9be6187cfff52edfac7c51b1834a47995d7
        with:
          distribution: goreleaser
          version: v0.176.0
          args: build --snapshot --rm-dist --skip-post-hooks --skip-validate
